### ISSUE TITLE
Background images do not work at all.

### ISSUE THREAD

**Issue by teamfunnels** [kaoz70/grapesjs-blocks-bootstrap4#26] opened 2020-02-14 05:50 UTC
I cannot see any background images in the style manager and if I set one it does not show up in the canvas.

**Comment by kaoz70** [comment] 2020-02-25 03:55
Background images are not specific to this plugin, maybe you should check GrapeJS docs for this. Or is there something I am missing? Could you please elaborate on what you are trying to accomplish with Bootstrap 4 and GrapesJS with background images?

**Comment by kaoz70** [comment] 2020-06-04 02:20
I'm closing this issue, if you think that the background error if caused by this plugin feel free to reopen it again.

**Closed as completed by kaoz70** 2020-06-04 02:20 UTC
Labels: invalid
