### ISSUE TITLE
Have problem with js file

### ISSUE THREAD

**Issue by bohdan-jdev0** [kaoz70/grapesjs-blocks-bootstrap4#9] opened 2018-04-25 15:14 UTC
Hello z1lk!
When I try to connect this file 'grapesjs-blocks-bootstrap4.min.js' i have the error
" Uncaught SyntaxError: Unexpected token } " - can you help me with it?

**Comment by Neira13** [comment] 2018-06-10 03:03
Hello @soxepo! I cannot reproduce your problem 🐱

**Comment by kaoz70** [comment] 2020-06-04 02:05
I'm closing this issue because its old and not reproducible.

**Closed as completed by kaoz70** 2020-06-04 02:05 UTC
